name: Release

on:
  pull_request:
    types: ["closed"]
  issue_comment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone PR branch
        uses: actions/checkout@v2
      - name: Create release
        uses: ElisaOyj/gh-action-pr-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease_id: "rc"
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
